export enum AuthType {
  LOGIN_EMPLOYEE = '@Auth/LOGIN_EMPLOYEE',
  LOGIN_REPAIRMAN = '@Auth/LOGIN_REPAIRMAN',
  LOGIN_ADMIN = '@Auth/LOGIN_ADMIN',
  LOGIN_SUCCESS = '@Auth/LOGIN_SUCCESS',
  LOGIN_FAIL = '@Auth/LOGIN_FAIL',
  LOGOUT = '@Auth/LOGOUT',

  FETCH_ME = '@Auth/FETCH_ME',
  FETCH_ME_SUCCESS = '@Auth/FETCH_ME_SUCCESS',
  FETCH_ME_FAIL = '@Auth/FETCH_ME_FAIL',
}
